### ISSUE TITLE
Integrate WL code

### ISSUE THREAD

**Issue by pli888** [pli888/gigadb-website#16]
- [x] [Build Choose upload or wizard page](https://github.com/pli888/gigadb-website/issues/2)
- [x] [Build Spreadsheet upload page](https://github.com/pli888/gigadb-website/issues/3)
- [x] [Wizard to accept spreadsheet upload](https://github.com/gigascience/gigadb-website/issues/102)
- [x] [Dataset Upload page - Download template file error](https://github.com/gigascience/gigadb-website/issues/326)
- [x] [Email functionality for data submission wizard](https://github.com/pli888/gigadb-website/issues/11)
- [x] [Update Create Dataset Study tab form](https://github.com/pli888/gigadb-website/issues/4)
- [x] [Title length warning in admin and wizard pages](https://github.com/gigascience/gigadb-website/issues/112)
- [x] [Image thumbnail generator](https://github.com/gigascience/gigadb-website/issues/240)
- [x] [image thumbnail bug](https://github.com/gigascience/gigadb-website/issues/337)
- [x] [Update Create Dataset Author tab form](https://github.com/pli888/gigadb-website/issues/5)
- [x] [Contributor roles](https://github.com/gigascience/gigadb-website/issues/91)
- [x] [Build Create Dataset Additional Info tab form](https://github.com/pli888/gigadb-website/issues/6)
- [x] [Add manuscript linking ability to wizard](https://github.com/gigascience/gigadb-website/issues/238)
- [x] [Add protocols section to wizard](https://github.com/gigascience/gigadb-website/issues/110)
- [x] [Build Create Dataset Funding tab form](https://github.com/gigascience/gigadb-website/issues/211)
- [x] [Update Create Dataset Sample tab form](https://github.com/pli888/gigadb-website/issues/8)
- [x] [Build Create Dataset Success page](https://github.com/pli888/gigadb-website/issues/10)
- [x] [Build Create Dataset Files tab form](https://github.com/pli888/gigadb-website/issues/9)
- [x] [Dataset status changes](https://github.com/gigascience/gigadb-website/issues/250)
- [x] [Add undo function into Your datasets tab on Profile page](https://github.com/gigascience/gigadb-website/issues/212)
- [x] [Add private accession links from Submitter profile page](https://github.com/gigascience/gigadb-website/issues/101)
- [x] [Submission wizard practice area](https://github.com/gigascience/gigadb-website/issues/72)
