### ISSUE TITLE
Fix WL bugs

### ISSUE THREAD

**Issue by pli888** [pli888/gigadb-website#17]
- [x] [Bug fixes to github version](https://github.com/gigascience/gigadb-website/issues/293)
- [ ] [Problem with creating a new user](https://github.com/gigascience/gigadb-website/issues/407)
- [ ] ~~[New Admin page for update/edit/create Sample Templates](https://github.com/gigascience/gigadb-website/issues/403)~~
- [x] [Samples admin page not working](https://github.com/gigascience/gigadb-website/issues/402)
- [x] [Move GitHub link within WL submission wizard](https://github.com/gigascience/gigadb-website/issues/401)
- [x] [GitHub link in wrong place in wizard](https://github.com/gigascience/gigadb-website/issues/400)
- [x] [Filter on columns in Admin tables not working](https://github.com/gigascience/gigadb-website/issues/399)
- [ ] [Dataset ID not appearing in create Dataset:File link page](https://github.com/gigascience/gigadb-website/issues/398)
- [x] [Error comiting curation log updates](https://github.com/gigascience/gigadb-website/issues/397)
- [x] [No update of curation log](https://github.com/gigascience/gigadb-website/issues/396)
- [x] [Missing information icons on Sample tab](https://github.com/gigascience/gigadb-website/issues/395)
- [x] [Species not being recognised](https://github.com/gigascience/gigadb-website/issues/394)
- [x] [Sample templates missing](https://github.com/gigascience/gigadb-website/issues/393)
- [x] [Missing info points](https://github.com/gigascience/gigadb-website/issues/392)
- [x] [CrediT dropdown menu missing from Author tab](https://github.com/gigascience/gigadb-website/issues/391)
- [x] [Vague error message when uploading Author list TSV file](https://github.com/gigascience/gigadb-website/issues/390)
- [x] [Nothing happens when you click extra tabs on submission wizard](https://github.com/gigascience/gigadb-website/issues/389)
- [x] [Pointless additional click required on first page of wizard](https://github.com/gigascience/gigadb-website/issues/388)
